package MusicTheoryLang.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class MajorScale_Constraints extends BaseConstraintsDescriptor {
  public MajorScale_Constraints() {
    super(CONCEPTS.MajorScale$vK);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept MajorScale$vK = MetaAdapterFactory.getConcept(0x87d1018d30c44219L, 0x852f1bd942b093e8L, 0x7c255ef757d6b824L, "MusicTheoryLang.structure.MajorScale");
  }
}
