package MusicTheoryLang.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_NoteNameNormalized extends EnumerationDescriptorBase {

  public EnumerationDescriptor_NoteNameNormalized() {
    super(0x87d1018d30c44219L, 0x852f1bd942b093e8L, 0x7c255ef757ceeed7L, "NoteNameNormalized", "r:e8bf4a00-4d2c-41d0-918b-66974261049f(MusicTheoryLang.structure)/8945660651264470743");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_C_0 = new EnumerationDescriptor.MemberDescriptor("C", "C", 0x7c255ef757ceef62L, "r:e8bf4a00-4d2c-41d0-918b-66974261049f(MusicTheoryLang.structure)/8945660651264470882");
  private final EnumerationDescriptor.MemberDescriptor myMember_CSharp_0 = new EnumerationDescriptor.MemberDescriptor("CSharp", "C♯", 0x7c255ef757ceef63L, "r:e8bf4a00-4d2c-41d0-918b-66974261049f(MusicTheoryLang.structure)/8945660651264470883");
  private final EnumerationDescriptor.MemberDescriptor myMember_D_0 = new EnumerationDescriptor.MemberDescriptor("D", "D", 0x7c255ef757ceef65L, "r:e8bf4a00-4d2c-41d0-918b-66974261049f(MusicTheoryLang.structure)/8945660651264470885");
  private final EnumerationDescriptor.MemberDescriptor myMember_DSharp_0 = new EnumerationDescriptor.MemberDescriptor("DSharp", "D♯", 0x7c255ef757ceef66L, "r:e8bf4a00-4d2c-41d0-918b-66974261049f(MusicTheoryLang.structure)/8945660651264470886");
  private final EnumerationDescriptor.MemberDescriptor myMember_E_0 = new EnumerationDescriptor.MemberDescriptor("E", "E", 0x7c255ef757ceef68L, "r:e8bf4a00-4d2c-41d0-918b-66974261049f(MusicTheoryLang.structure)/8945660651264470888");
  private final EnumerationDescriptor.MemberDescriptor myMember_F_0 = new EnumerationDescriptor.MemberDescriptor("F", "F", 0x7c255ef757ceef69L, "r:e8bf4a00-4d2c-41d0-918b-66974261049f(MusicTheoryLang.structure)/8945660651264470889");
  private final EnumerationDescriptor.MemberDescriptor myMember_FSharp_0 = new EnumerationDescriptor.MemberDescriptor("FSharp", "F♯", 0x7c255ef757ceef6aL, "r:e8bf4a00-4d2c-41d0-918b-66974261049f(MusicTheoryLang.structure)/8945660651264470890");
  private final EnumerationDescriptor.MemberDescriptor myMember_G_0 = new EnumerationDescriptor.MemberDescriptor("G", "G", 0x7c255ef757ceef6cL, "r:e8bf4a00-4d2c-41d0-918b-66974261049f(MusicTheoryLang.structure)/8945660651264470892");
  private final EnumerationDescriptor.MemberDescriptor myMember_GSharp_0 = new EnumerationDescriptor.MemberDescriptor("GSharp", "G♯", 0x7c255ef757ceef6dL, "r:e8bf4a00-4d2c-41d0-918b-66974261049f(MusicTheoryLang.structure)/8945660651264470893");
  private final EnumerationDescriptor.MemberDescriptor myMember_A_0 = new EnumerationDescriptor.MemberDescriptor("A", "A", 0x7c255ef757ceef6fL, "r:e8bf4a00-4d2c-41d0-918b-66974261049f(MusicTheoryLang.structure)/8945660651264470895");
  private final EnumerationDescriptor.MemberDescriptor myMember_ASharp_0 = new EnumerationDescriptor.MemberDescriptor("ASharp", "A♯", 0x7c255ef757ceef70L, "r:e8bf4a00-4d2c-41d0-918b-66974261049f(MusicTheoryLang.structure)/8945660651264470896");
  private final EnumerationDescriptor.MemberDescriptor myMember_B_0 = new EnumerationDescriptor.MemberDescriptor("B", "B", 0x7c255ef757ceef72L, "r:e8bf4a00-4d2c-41d0-918b-66974261049f(MusicTheoryLang.structure)/8945660651264470898");
  private final EnumerationDescriptor.MemberDescriptor myMember_unknown_0 = new EnumerationDescriptor.MemberDescriptor("unknown", "unknown", 0x7c255ef757d00eecL, "r:e8bf4a00-4d2c-41d0-918b-66974261049f(MusicTheoryLang.structure)/8945660651264544492");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x87d1018d30c44219L, 0x852f1bd942b093e8L, 0x7c255ef757ceeed7L, 0x7c255ef757ceef62L, 0x7c255ef757ceef63L, 0x7c255ef757ceef65L, 0x7c255ef757ceef66L, 0x7c255ef757ceef68L, 0x7c255ef757ceef69L, 0x7c255ef757ceef6aL, 0x7c255ef757ceef6cL, 0x7c255ef757ceef6dL, 0x7c255ef757ceef6fL, 0x7c255ef757ceef70L, 0x7c255ef757ceef72L, 0x7c255ef757d00eecL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_C_0, myMember_CSharp_0, myMember_D_0, myMember_DSharp_0, myMember_E_0, myMember_F_0, myMember_FSharp_0, myMember_G_0, myMember_GSharp_0, myMember_A_0, myMember_ASharp_0, myMember_B_0, myMember_unknown_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "C":
        return myMember_C_0;
      case "CSharp":
        return myMember_CSharp_0;
      case "D":
        return myMember_D_0;
      case "DSharp":
        return myMember_DSharp_0;
      case "E":
        return myMember_E_0;
      case "F":
        return myMember_F_0;
      case "FSharp":
        return myMember_FSharp_0;
      case "G":
        return myMember_G_0;
      case "GSharp":
        return myMember_GSharp_0;
      case "A":
        return myMember_A_0;
      case "ASharp":
        return myMember_ASharp_0;
      case "B":
        return myMember_B_0;
      case "unknown":
        return myMember_unknown_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
