package MusicTheoryLang.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_MuscalMode extends EnumerationDescriptorBase {

  public EnumerationDescriptor_MuscalMode() {
    super(0x87d1018d30c44219L, 0x852f1bd942b093e8L, 0x7c255ef757dc4b0fL, "MuscalMode", "r:e8bf4a00-4d2c-41d0-918b-66974261049f(MusicTheoryLang.structure)/8945660651265346319");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Ionian_0 = new EnumerationDescriptor.MemberDescriptor("Ionian", "Ionian", 0x7c255ef757dc4b10L, "r:e8bf4a00-4d2c-41d0-918b-66974261049f(MusicTheoryLang.structure)/8945660651265346320");
  private final EnumerationDescriptor.MemberDescriptor myMember_Dorian_0 = new EnumerationDescriptor.MemberDescriptor("Dorian", "Dorian", 0x7c255ef757dc4b12L, "r:e8bf4a00-4d2c-41d0-918b-66974261049f(MusicTheoryLang.structure)/8945660651265346322");
  private final EnumerationDescriptor.MemberDescriptor myMember_Phrygian_0 = new EnumerationDescriptor.MemberDescriptor("Phrygian", "Phrygian", 0x7c255ef757dc4b16L, "r:e8bf4a00-4d2c-41d0-918b-66974261049f(MusicTheoryLang.structure)/8945660651265346326");
  private final EnumerationDescriptor.MemberDescriptor myMember_Lydian_0 = new EnumerationDescriptor.MemberDescriptor("Lydian", "Lydian", 0x7c255ef757dc4b1dL, "r:e8bf4a00-4d2c-41d0-918b-66974261049f(MusicTheoryLang.structure)/8945660651265346333");
  private final EnumerationDescriptor.MemberDescriptor myMember_Mixolydian_0 = new EnumerationDescriptor.MemberDescriptor("Mixolydian", "Mixolydian", 0x7c255ef757dc4b23L, "r:e8bf4a00-4d2c-41d0-918b-66974261049f(MusicTheoryLang.structure)/8945660651265346339");
  private final EnumerationDescriptor.MemberDescriptor myMember_Aeolian_0 = new EnumerationDescriptor.MemberDescriptor("Aeolian", "Aeolian", 0x7c255ef757dc4b2aL, "r:e8bf4a00-4d2c-41d0-918b-66974261049f(MusicTheoryLang.structure)/8945660651265346346");
  private final EnumerationDescriptor.MemberDescriptor myMember_Locrian_0 = new EnumerationDescriptor.MemberDescriptor("Locrian", "Locrian", 0x7c255ef757dc4b32L, "r:e8bf4a00-4d2c-41d0-918b-66974261049f(MusicTheoryLang.structure)/8945660651265346354");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x87d1018d30c44219L, 0x852f1bd942b093e8L, 0x7c255ef757dc4b0fL, 0x7c255ef757dc4b10L, 0x7c255ef757dc4b12L, 0x7c255ef757dc4b16L, 0x7c255ef757dc4b1dL, 0x7c255ef757dc4b23L, 0x7c255ef757dc4b2aL, 0x7c255ef757dc4b32L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Ionian_0, myMember_Dorian_0, myMember_Phrygian_0, myMember_Lydian_0, myMember_Mixolydian_0, myMember_Aeolian_0, myMember_Locrian_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Ionian":
        return myMember_Ionian_0;
      case "Dorian":
        return myMember_Dorian_0;
      case "Phrygian":
        return myMember_Phrygian_0;
      case "Lydian":
        return myMember_Lydian_0;
      case "Mixolydian":
        return myMember_Mixolydian_0;
      case "Aeolian":
        return myMember_Aeolian_0;
      case "Locrian":
        return myMember_Locrian_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
