package MusicTheoryLang.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_NoteName extends EnumerationDescriptorBase {

  public EnumerationDescriptor_NoteName() {
    super(0x87d1018d30c44219L, 0x852f1bd942b093e8L, 0x7c255ef757c92c0dL, "NoteName", "r:e8bf4a00-4d2c-41d0-918b-66974261049f(MusicTheoryLang.structure)/8945660651264093197");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_C_0 = new EnumerationDescriptor.MemberDescriptor("C", "C", 0x7c255ef757c92c0eL, "r:e8bf4a00-4d2c-41d0-918b-66974261049f(MusicTheoryLang.structure)/8945660651264093198");
  private final EnumerationDescriptor.MemberDescriptor myMember_CSharp_0 = new EnumerationDescriptor.MemberDescriptor("CSharp", "C♯", 0x7c255ef757c92c33L, "r:e8bf4a00-4d2c-41d0-918b-66974261049f(MusicTheoryLang.structure)/8945660651264093235");
  private final EnumerationDescriptor.MemberDescriptor myMember_DFlat_0 = new EnumerationDescriptor.MemberDescriptor("DFlat", "D♭", 0x7c255ef757c92c55L, "r:e8bf4a00-4d2c-41d0-918b-66974261049f(MusicTheoryLang.structure)/8945660651264093269");
  private final EnumerationDescriptor.MemberDescriptor myMember_D_0 = new EnumerationDescriptor.MemberDescriptor("D", "D", 0x7c255ef757c92c83L, "r:e8bf4a00-4d2c-41d0-918b-66974261049f(MusicTheoryLang.structure)/8945660651264093315");
  private final EnumerationDescriptor.MemberDescriptor myMember_DSharp_0 = new EnumerationDescriptor.MemberDescriptor("DSharp", "D♯", 0x7c255ef757c92c9dL, "r:e8bf4a00-4d2c-41d0-918b-66974261049f(MusicTheoryLang.structure)/8945660651264093341");
  private final EnumerationDescriptor.MemberDescriptor myMember_EFlat_0 = new EnumerationDescriptor.MemberDescriptor("EFlat", "E♭", 0x7c255ef757c92cc2L, "r:e8bf4a00-4d2c-41d0-918b-66974261049f(MusicTheoryLang.structure)/8945660651264093378");
  private final EnumerationDescriptor.MemberDescriptor myMember_E_0 = new EnumerationDescriptor.MemberDescriptor("E", "E", 0x7c255ef757c92cc9L, "r:e8bf4a00-4d2c-41d0-918b-66974261049f(MusicTheoryLang.structure)/8945660651264093385");
  private final EnumerationDescriptor.MemberDescriptor myMember_F_0 = new EnumerationDescriptor.MemberDescriptor("F", "F", 0x7c255ef757c92ce6L, "r:e8bf4a00-4d2c-41d0-918b-66974261049f(MusicTheoryLang.structure)/8945660651264093414");
  private final EnumerationDescriptor.MemberDescriptor myMember_FSharp_0 = new EnumerationDescriptor.MemberDescriptor("FSharp", "F♯", 0x7c255ef757c92cefL, "r:e8bf4a00-4d2c-41d0-918b-66974261049f(MusicTheoryLang.structure)/8945660651264093423");
  private final EnumerationDescriptor.MemberDescriptor myMember_GFlat_0 = new EnumerationDescriptor.MemberDescriptor("GFlat", "G♭", 0x7c255ef757c92d23L, "r:e8bf4a00-4d2c-41d0-918b-66974261049f(MusicTheoryLang.structure)/8945660651264093475");
  private final EnumerationDescriptor.MemberDescriptor myMember_G_0 = new EnumerationDescriptor.MemberDescriptor("G", "G", 0x7c255ef757c92d4dL, "r:e8bf4a00-4d2c-41d0-918b-66974261049f(MusicTheoryLang.structure)/8945660651264093517");
  private final EnumerationDescriptor.MemberDescriptor myMember_GSharp_0 = new EnumerationDescriptor.MemberDescriptor("GSharp", "G♯", 0x7c255ef757c92d64L, "r:e8bf4a00-4d2c-41d0-918b-66974261049f(MusicTheoryLang.structure)/8945660651264093540");
  private final EnumerationDescriptor.MemberDescriptor myMember_AFlat_0 = new EnumerationDescriptor.MemberDescriptor("AFlat", "A♭", 0x7c255ef757c92d90L, "r:e8bf4a00-4d2c-41d0-918b-66974261049f(MusicTheoryLang.structure)/8945660651264093584");
  private final EnumerationDescriptor.MemberDescriptor myMember_A_0 = new EnumerationDescriptor.MemberDescriptor("A", "A", 0x7c255ef757c92da9L, "r:e8bf4a00-4d2c-41d0-918b-66974261049f(MusicTheoryLang.structure)/8945660651264093609");
  private final EnumerationDescriptor.MemberDescriptor myMember_ASharp_0 = new EnumerationDescriptor.MemberDescriptor("ASharp", "A♯", 0x7c255ef757c92dcdL, "r:e8bf4a00-4d2c-41d0-918b-66974261049f(MusicTheoryLang.structure)/8945660651264093645");
  private final EnumerationDescriptor.MemberDescriptor myMember_BFlat_0 = new EnumerationDescriptor.MemberDescriptor("BFlat", "B♭", 0x7c255ef757c92dfcL, "r:e8bf4a00-4d2c-41d0-918b-66974261049f(MusicTheoryLang.structure)/8945660651264093692");
  private final EnumerationDescriptor.MemberDescriptor myMember_B_0 = new EnumerationDescriptor.MemberDescriptor("B", "B", 0x7c255ef757c92e17L, "r:e8bf4a00-4d2c-41d0-918b-66974261049f(MusicTheoryLang.structure)/8945660651264093719");
  private final EnumerationDescriptor.MemberDescriptor myMember_Unknown_0 = new EnumerationDescriptor.MemberDescriptor("Unknown", "?", 0x7c255ef757d8e327L, "r:e8bf4a00-4d2c-41d0-918b-66974261049f(MusicTheoryLang.structure)/8945660651265123111");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x87d1018d30c44219L, 0x852f1bd942b093e8L, 0x7c255ef757c92c0dL, 0x7c255ef757c92c0eL, 0x7c255ef757c92c33L, 0x7c255ef757c92c55L, 0x7c255ef757c92c83L, 0x7c255ef757c92c9dL, 0x7c255ef757c92cc2L, 0x7c255ef757c92cc9L, 0x7c255ef757c92ce6L, 0x7c255ef757c92cefL, 0x7c255ef757c92d23L, 0x7c255ef757c92d4dL, 0x7c255ef757c92d64L, 0x7c255ef757c92d90L, 0x7c255ef757c92da9L, 0x7c255ef757c92dcdL, 0x7c255ef757c92dfcL, 0x7c255ef757c92e17L, 0x7c255ef757d8e327L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_C_0, myMember_CSharp_0, myMember_DFlat_0, myMember_D_0, myMember_DSharp_0, myMember_EFlat_0, myMember_E_0, myMember_F_0, myMember_FSharp_0, myMember_GFlat_0, myMember_G_0, myMember_GSharp_0, myMember_AFlat_0, myMember_A_0, myMember_ASharp_0, myMember_BFlat_0, myMember_B_0, myMember_Unknown_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "C":
        return myMember_C_0;
      case "CSharp":
        return myMember_CSharp_0;
      case "DFlat":
        return myMember_DFlat_0;
      case "D":
        return myMember_D_0;
      case "DSharp":
        return myMember_DSharp_0;
      case "EFlat":
        return myMember_EFlat_0;
      case "E":
        return myMember_E_0;
      case "F":
        return myMember_F_0;
      case "FSharp":
        return myMember_FSharp_0;
      case "GFlat":
        return myMember_GFlat_0;
      case "G":
        return myMember_G_0;
      case "GSharp":
        return myMember_GSharp_0;
      case "AFlat":
        return myMember_AFlat_0;
      case "A":
        return myMember_A_0;
      case "ASharp":
        return myMember_ASharp_0;
      case "BFlat":
        return myMember_BFlat_0;
      case "B":
        return myMember_B_0;
      case "Unknown":
        return myMember_Unknown_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
